### ISSUE TITLE
How to undo Sadcoy changes

### ISSUE THREAD

**Issue by Laviesss** [Jisll/Sadcoy#3]
How do I undo the changes, I no longer see my run box history, not sure if Sadcoy caused it and also I see my device and browser is being managed and I want to remove this

**Comment by Jisll** [comment]
There is no way back, the only way back is if you change the files with Visual Studio, that means you have to change all the registries that are present in Optimze.cs

**Comment by LavieGamer** [comment]
So what exactly do I have to change in the registires, I do not know a lot about them other than if you mess them up, you basically destroyed your pc/programs

**Comment by Jisll** [comment]
I have taken only registries that do not destroy anything on the PC in a big way, they are safe to change and remove unnecessary functions of the Windows operating system. I can release a version where you can reset everything back to the default.

**Comment by LavieGamer** [comment]
Please do

**Comment by Jisll** [comment]
uploaded new version, you can go back to standard now.

**Comment by Laviesss** [comment]
I also forgot to tell you when I pressed run optimization, it always freezed

**Comment by Jisll** [comment]
I also forgot to tell you when I pressed run optimization, it always freezed

Maybe its freezed because its working in your background, he changes everything in your background.
If it crashes try start it with administrator.
