### ISSUE TITLE
Systemwiederherstellungspunkt erstellen

### ISSUE THREAD

**Issue by Marvin700** [Jisll/Sadcoy#6]
Moin,
habe dein Tool eben mal ausgetestet und da wird ja gar kein Systemwiederherstellungspunkt erstellt.
Ich raff leider die Pull reuest in GitHub nicht, deswegen schreib ich dir das hier.

So habe ich es bei mir im Tool Umgesetzt:
```
Enable-ComputerRestore -Drive "C:\"
REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /V "SystemRestorePointCreationFrequency" /T REG_DWORD /D 0 /F
Checkpoint-Computer -Description "Windows_Optimisation_Pack" -RestorePointType MODIFY_SETTINGS
REG DELETE "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /V "SystemRestorePointCreationFrequency" /F }
```

PS: Die Oberfläche des Tools ist mega!

**Comment by Jisll** [comment]
Die Pull-Anfrage funktioniert wie folgt, Du "forkst" das Projekt und bearbeitest es, dann kannst Du eine Pull-Anfrage dafür erstellen und sie wird hier bei mir geöffnet.
